name: bvhar-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - libboost-headers>=1.88.0
  - eigen>=3.4.0
  - spdlog
  - pybind11
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - jupyter
  - pip:
      - quartodoc
