name: bvhar-env
channels:
  - conda-forge
dependencies:
  - boost-cpp>=1.84.0
  - eigen>=3.4.0
  - numpy
  - pandas
  - pip
  - pybind11
  - llvm-openmp
  - pytest
  - python>=3.10
  - pip:
      - quartodoc
