name: bvhar-env
channels:
  - conda-forge
dependencies:
  - boost-cpp=1.85.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - colorama=0.4.6
  - eigen=3.4.0
  - exceptiongroup=1.2.2
  - icu=75.1
  - iniconfig=2.0.0
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - ncurses=6.5
  - numpy=2.1.0
  - openssl=3.3.1
  - packaging=24.1
  - pip=24.2
  - pluggy=1.5.0
  - pybind11=2.13.5
  - pybind11-global=2.13.5
  - pytest=8.3.2
  - python=3.11.9
  - python_abi=3.11
  - readline=8.2
  - setuptools=72.2.0
  - tk=8.6.13
  - tomli=2.0.1
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
  - zstd=1.5.6
