name: bvhar-env
channels:
  - conda-forge
dependencies:
  - boost-cpp=1.85.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - colorama=0.4.6
  - eigen=3.4.0
  - exceptiongroup=1.2.2
  - icu=75.1
  - iniconfig=2.0.0
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - ncurses=6.5
  - numpy=2.1.0
  - openssl=3.3.1
  - packaging=24.1
  - pip=24.2
  - pluggy=1.5.0
  - pybind11=2.13.5
  - pybind11-global=2.13.5
  - pytest=8.3.2
  - python=3.11.9
  - python_abi=3.11
  - readline=8.2
  - setuptools=72.2.0
  - tk=8.6.13
  - tomli=2.0.1
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - attrs==24.2.0
      - beartype==0.18.5
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - griffe==1.2.0
      - idna==3.8
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - plum-dispatch==2.5.2
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pyyaml==6.0.2
      - quartodoc==0.7.6
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.20.0
      - sphobjinv==2.3.1.1
      - tabulate==0.9.0
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - watchdog==4.0.2
      - zipp==3.20.0
