[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bvhar"
version = "0.0.0.9000"
license = {file = "LICENSE"}
description = "BVHAR"
authors = [{name = "Young Geun Kim", email = "ygeunkimstat@gmail.com"}]
maintainers = [{name = "Young Geun Kim", email = "ygeunkimstat@gmail.com"}]
requires-python = ">=3.10"
readme = "README.md"
classifiers = [
    'Intended Audience :: Science/Research',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3'
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["bvhar", "bvhar.*"]
namespaces = false

[tool.setuptools.exclude-package-data]
"*" = ["*.cpp", "*.h"]

[project.optional-dependencies]
test = ["pytest"]
