on:
    push:
      branches: [feature/python] # change to [main, master, 'hotfix/*', 'release/*', develop] after finishing the branch
    pull_request:
      branches: [feature/python] # change to [main, master, 'hotfix/*', 'release/*', develop] after finishing the branch

name: Python wheel installation

jobs:
  test-pip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        working-directory: python
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install requirements
        run: pip install -r requirements/requirements.txt
      
      - name: Build wheel
        run: python setup.py bdist_wheel
      
      - name: Install from wheel
        run: pip install dist/bvhar-*.whl
      
      - name: Run tests
        run: pytest tests
