on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

name: quartodoc

jobs:
  quartodoc:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          activate-environment: bvhar-dev
          environment-file: python/requirements/environment-dev.yml
          python-version: '3.11'
          auto-activate-base: false

      - name: Install
        run: conda run -n bvhar-dev pip install -e . -v
        working-directory: python
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Check quartodoc version
        run: sed -i "s|QUARTODOC_VERSION|$(python -c 'import importlib.metadata; print(importlib.metadata.version("quartodoc"))')|" _variables.yml
        working-directory: python/docs
      
      - name: Main and develop
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" == "develop" ]; then
            echo "TARGET_FOLDER=package/bvhar/dev/python" >> $GITHUB_ENV
            sed -i 's|VERSION_REF|https://github.com/ygeunkim/bvhar/tree/develop/python|; s|R_VERSION_REF|https://ygeunkim.github.io/package/bvhar/|' _variables.yml
          else
            echo "TARGET_FOLDER=package/bvhar/python" >> $GITHUB_ENV
            sed -i 's|VERSION_REF|https://github.com/ygeunkim/bvhar/tree/master/python|; s|R_VERSION_REF|https://ygeunkim.github.io/package/bvhar/dev/|' _variables.yml
          fi
        working-directory: python/docs

      - name: Build site
        run: |
            conda run -n bvhar-dev quartodoc build
            conda run -n bvhar-dev quarto render .
        working-directory: python/docs

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          token: ${{ secrets.YGEUNKIM_PAGE_PAT }}
          repository-name: ygeunkim/ygeunkim.github.io
          clean: false
          branch: master
          folder: python/docs/_site
          target-folder: ${{ env.TARGET_FOLDER }}
